-- AUTOGENERATED BY storj.io/dbx
-- DO NOT EDIT
CREATE TABLE data_blobs (
	id bytea NOT NULL,
	PRIMARY KEY ( id )
) ;
CREATE TABLE data_dates (
	id date NOT NULL,
	PRIMARY KEY ( id )
) ;
CREATE TABLE data_floats (
	id real NOT NULL,
	PRIMARY KEY ( id )
) ;
CREATE TABLE data_float64s (
	id double precision NOT NULL,
	PRIMARY KEY ( id )
) ;
CREATE TABLE data_ints (
	id integer NOT NULL,
	PRIMARY KEY ( id )
) ;
CREATE TABLE data_int64s (
	id bigint NOT NULL,
	PRIMARY KEY ( id )
) ;
CREATE TABLE data_jsons (
	id jsonb NOT NULL,
	PRIMARY KEY ( id )
) ;
CREATE TABLE data_serials (
	id serial NOT NULL,
	PRIMARY KEY ( id )
) ;
CREATE TABLE data_serial64s (
	id bigserial NOT NULL,
	PRIMARY KEY ( id )
) ;
CREATE TABLE data_texts (
	id text NOT NULL,
	PRIMARY KEY ( id )
) ;
CREATE TABLE data_timestamps (
	id timestamp with time zone NOT NULL,
	PRIMARY KEY ( id )
) ;
CREATE TABLE data_uints (
	id integer NOT NULL,
	PRIMARY KEY ( id )
) ;
CREATE TABLE data_uint64s (
	id bigint NOT NULL,
	PRIMARY KEY ( id )
) ;
CREATE TABLE data_utimestamps (
	id timestamp NOT NULL,
	PRIMARY KEY ( id )
)
