-- AUTOGENERATED BY storj.io/dbx
-- DO NOT EDIT
CREATE TABLE data_blobs (
	id BYTES(MAX) NOT NULL
) PRIMARY KEY ( id ) ;
CREATE TABLE data_dates (
	id DATE NOT NULL
) PRIMARY KEY ( id ) ;
CREATE TABLE data_floats (
	id FLOAT32 NOT NULL
) PRIMARY KEY ( id ) ;
CREATE TABLE data_float64s (
	id FLOAT64 NOT NULL
) PRIMARY KEY ( id ) ;
CREATE TABLE data_ints (
	id INT64 NOT NULL
) PRIMARY KEY ( id ) ;
CREATE TABLE data_int64s (
	id INT64 NOT NULL
) PRIMARY KEY ( id ) ;
CREATE TABLE data_jsons (
	id JSON NOT NULL
) PRIMARY KEY ( id ) ;
CREATE SEQUENCE data_serials_id OPTIONS (sequence_kind='bit_reversed_positive') ;
CREATE TABLE data_serials (
	id INT64 NOT NULL DEFAULT (GET_NEXT_SEQUENCE_VALUE(SEQUENCE data_serials_id))
) PRIMARY KEY ( id ) ;
CREATE SEQUENCE data_serial64s_id OPTIONS (sequence_kind='bit_reversed_positive') ;
CREATE TABLE data_serial64s (
	id INT64 NOT NULL DEFAULT (GET_NEXT_SEQUENCE_VALUE(SEQUENCE data_serial64s_id))
) PRIMARY KEY ( id ) ;
CREATE TABLE data_texts (
	id STRING(MAX) NOT NULL
) PRIMARY KEY ( id ) ;
CREATE TABLE data_timestamps (
	id TIMESTAMP NOT NULL
) PRIMARY KEY ( id ) ;
CREATE TABLE data_uints (
	id INT64 NOT NULL
) PRIMARY KEY ( id ) ;
CREATE TABLE data_uint64s (
	id INT64 NOT NULL
) PRIMARY KEY ( id ) ;
CREATE TABLE data_utimestamps (
	id TIMESTAMP NOT NULL
) PRIMARY KEY ( id )
