-- AUTOGENERATED BY storj.io/dbx
-- DO NOT EDIT
CREATE TABLE people (
	pk INTEGER NOT NULL,
	name TEXT NOT NULL,
	value TEXT NOT NULL,
	value_up TEXT NOT NULL,
	value_null TEXT,
	value_null_up TEXT,
	PRIMARY KEY ( pk )
)
