-- AUTOGENERATED BY storj.io/dbx
-- DO NOT EDIT
CREATE SEQUENCE a_id OPTIONS (sequence_kind='bit_reversed_positive') ;
CREATE TABLE a (
	id INT64 NOT NULL DEFAULT (GET_NEXT_SEQUENCE_VALUE(SEQUENCE a_id))
) PRIMARY KEY ( id ) ;
CREATE SEQUENCE b_id OPTIONS (sequence_kind='bit_reversed_positive') ;
CREATE TABLE b (
	id INT64 NOT NULL DEFAULT (GET_NEXT_SEQUENCE_VALUE(SEQUENCE b_id)),
	a_id INT64 NOT NULL,
	CONSTRAINT b_a_id_fkey FOREIGN KEY (a_id) REFERENCES a (id)
) PRIMARY KEY ( id ) ;
CREATE SEQUENCE c_id OPTIONS (sequence_kind='bit_reversed_positive') ;
CREATE TABLE c (
	id INT64 NOT NULL DEFAULT (GET_NEXT_SEQUENCE_VALUE(SEQUENCE c_id)),
	lat FLOAT64 NOT NULL,
	lon FLOAT64 NOT NULL,
	b_id INT64 NOT NULL,
	CONSTRAINT c_b_id_fkey FOREIGN KEY (b_id) REFERENCES b (id)
) PRIMARY KEY ( id ) ;
CREATE UNIQUE INDEX index_c_b_id ON c (b_id)
