// AUTOGENERATED BY storj.io/dbx
// DO NOT EDIT.

package wrap_type

import (
	"bytes"
	"context"
	"database/sql"
	"errors"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"
	"unicode"

	_ "cloud.google.com/go/spanner"
	"crypto/rand"
	sqldriver "database/sql/driver"
	_ "github.com/googleapis/go-sql-spanner"
	"github.com/jackc/pgx/v5/pgconn"
	_ "github.com/jackc/pgx/v5/stdlib"
	"github.com/mattn/go-sqlite3"
	"math"
)

// Prevent conditional imports from causing build failures.
var _ = strconv.Itoa
var _ = strings.LastIndex
var _ = fmt.Sprint
var _ sync.Mutex

var (
	WrapErr = func(err *Error) error { return err }
	Logger  func(format string, args ...any)

	errTooManyRows       = errors.New("too many rows")
	errUnsupportedDriver = errors.New("unsupported driver")
	errEmptyUpdate       = errors.New("empty update")
)

func logError(format string, args ...any) {
	if Logger != nil {
		Logger(format, args...)
	}
}

type ErrorCode int

const (
	ErrorCode_Unknown ErrorCode = iota
	ErrorCode_UnsupportedDriver
	ErrorCode_NoRows
	ErrorCode_TxDone
	ErrorCode_TooManyRows
	ErrorCode_ConstraintViolation
	ErrorCode_EmptyUpdate
)

type Error struct {
	Err         error
	Code        ErrorCode
	Driver      string
	Constraint  string
	QuerySuffix string
}

func (e *Error) Error() string {
	return e.Err.Error()
}

func (e *Error) Unwrap() error {
	return e.Err
}

func wrapErr(e *Error) error {
	if WrapErr == nil {
		return e
	}
	return WrapErr(e)
}

func makeErr(err error) error {
	if err == nil {
		return nil
	}
	var e *Error
	if errors.As(err, &e) {
		return wrapErr(e)
	}
	e = &Error{Err: err}
	switch err {
	case sql.ErrNoRows:
		e.Code = ErrorCode_NoRows
	case sql.ErrTxDone:
		e.Code = ErrorCode_TxDone
	}
	return wrapErr(e)
}

func unsupportedDriver(driver string) error {
	return wrapErr(&Error{
		Err:    errUnsupportedDriver,
		Code:   ErrorCode_UnsupportedDriver,
		Driver: driver,
	})
}

func emptyUpdate() error {
	return wrapErr(&Error{
		Err:  errEmptyUpdate,
		Code: ErrorCode_EmptyUpdate,
	})
}

func tooManyRows(query_suffix string) error {
	return wrapErr(&Error{
		Err:         errTooManyRows,
		Code:        ErrorCode_TooManyRows,
		QuerySuffix: query_suffix,
	})
}

func constraintViolation(err error, constraint string) error {
	return wrapErr(&Error{
		Err:        err,
		Code:       ErrorCode_ConstraintViolation,
		Constraint: constraint,
	})
}

type driver interface {
	ExecContext(ctx context.Context, query string, args ...any) (sql.Result, error)
	QueryContext(ctx context.Context, query string, args ...any) (*sql.Rows, error)
	QueryRowContext(ctx context.Context, query string, args ...any) *sql.Row
}

type DB struct {
	*sql.DB
	dbMethods

	Hooks struct {
		Now func() time.Time
	}
}

func Open(driver, source string) (db *DB, err error) {
	var sql_db *sql.DB
	switch driver {
	case "sqlite3":
		sql_db, err = opensqlite3(source)
	case "pgx":
		sql_db, err = openpgx(source)
	case "pgxcockroach":
		sql_db, err = openpgxcockroach(source)
	case "spanner":
		sql_db, err = openspanner(source)
	default:
		return nil, unsupportedDriver(driver)
	}
	if err != nil {
		return nil, makeErr(err)
	}
	defer func(sql_db *sql.DB) {
		if err != nil {
			_ = sql_db.Close()
		}
	}(sql_db)

	if err := sql_db.Ping(); err != nil {
		return nil, makeErr(err)
	}

	db = &DB{
		DB: sql_db,
	}
	db.Hooks.Now = time.Now

	switch driver {
	case "sqlite3":
		db.dbMethods = newsqlite3(db)
	case "pgx":
		db.dbMethods = newpgx(db)
	case "pgxcockroach":
		db.dbMethods = newpgxcockroach(db)
	case "spanner":
		db.dbMethods = newspanner(db)
	default:
		return nil, unsupportedDriver(driver)
	}

	return db, nil
}

func (obj *DB) Close() (err error) {
	return obj.makeErr(obj.DB.Close())
}

func (obj *DB) Open(ctx context.Context) (*Tx, error) {
	tx, err := obj.DB.BeginTx(ctx, nil)
	if err != nil {
		return nil, obj.makeErr(err)
	}

	return &Tx{
		Tx:        tx,
		txMethods: obj.wrapTx(tx),
	}, nil
}

func DeleteAll(ctx context.Context, db *DB) (int64, error) {
	tx, err := db.Open(ctx)
	if err != nil {
		return 0, err
	}
	defer func() {
		if err == nil {
			err = db.makeErr(tx.Commit())
			return
		}

		if err_rollback := tx.Rollback(); err_rollback != nil {
			logError("delete-all: rollback failed: %v", db.makeErr(err_rollback))
		}
	}()
	return tx.deleteAll(ctx)
}

type Tx struct {
	Tx *sql.Tx
	txMethods
}

type dialectTx struct {
	tx *sql.Tx
}

func (tx *dialectTx) Commit() (err error) {
	return makeErr(tx.tx.Commit())
}

func (tx *dialectTx) Rollback() (err error) {
	return makeErr(tx.tx.Rollback())
}

type sqlite3Impl struct {
	db      *DB
	dialect __sqlbundle_sqlite3
	driver  driver
	txn     bool
}

func (obj *sqlite3Impl) Rebind(s string) string {
	return obj.dialect.Rebind(s)
}

func (obj *sqlite3Impl) logStmt(stmt string, args ...any) {
	sqlite3LogStmt(stmt, args...)
}

func (obj *sqlite3Impl) makeErr(err error) error {
	constraint, ok := obj.isConstraintError(err)
	if ok {
		return constraintViolation(err, constraint)
	}
	return makeErr(err)
}

type sqlite3DB struct {
	db *DB
	*sqlite3Impl
}

func newsqlite3(db *DB) *sqlite3DB {
	return &sqlite3DB{
		db: db,
		sqlite3Impl: &sqlite3Impl{
			db:     db,
			driver: db.DB,
		},
	}
}

func (obj *sqlite3DB) Schema() []string {
	return []string{

		`CREATE TABLE people (
	pk INTEGER NOT NULL,
	name TEXT NOT NULL,
	u64 INTEGER NOT NULL,
	u64_up INTEGER NOT NULL,
	u64_null INTEGER,
	u64_null_up INTEGER,
	PRIMARY KEY ( pk )
)`,
	}
}

func (obj *sqlite3DB) DropSchema() []string {
	return []string{

		`DROP TABLE IF EXISTS people`,
	}
}

func (obj *sqlite3DB) wrapTx(tx *sql.Tx) txMethods {
	return &sqlite3Tx{
		dialectTx: dialectTx{tx: tx},
		sqlite3Impl: &sqlite3Impl{
			db:     obj.db,
			driver: tx,
			txn:    true,
		},
	}
}

type sqlite3Tx struct {
	dialectTx
	*sqlite3Impl
}

func sqlite3LogStmt(stmt string, args ...any) {
	// TODO: render placeholders
	if Logger != nil {
		out := fmt.Sprintf("stmt: %s\nargs: %v\n", stmt, pretty(args))
		Logger(out)
	}
}

type pgxImpl struct {
	db      *DB
	dialect __sqlbundle_pgx
	driver  driver
	txn     bool
}

func (obj *pgxImpl) Rebind(s string) string {
	return obj.dialect.Rebind(s)
}

func (obj *pgxImpl) logStmt(stmt string, args ...any) {
	pgxLogStmt(stmt, args...)
}

func (obj *pgxImpl) makeErr(err error) error {
	constraint, ok := obj.isConstraintError(err)
	if ok {
		return constraintViolation(err, constraint)
	}
	return makeErr(err)
}

type pgxDB struct {
	db *DB
	*pgxImpl
}

func newpgx(db *DB) *pgxDB {
	return &pgxDB{
		db: db,
		pgxImpl: &pgxImpl{
			db:     db,
			driver: db.DB,
		},
	}
}

func (obj *pgxDB) Schema() []string {
	return []string{

		`CREATE TABLE people (
	pk bigserial NOT NULL,
	name text NOT NULL,
	u64 bigint NOT NULL,
	u64_up bigint NOT NULL,
	u64_null bigint,
	u64_null_up bigint,
	PRIMARY KEY ( pk )
)`,
	}
}

func (obj *pgxDB) DropSchema() []string {
	return []string{

		`DROP TABLE IF EXISTS people`,
	}
}

func (obj *pgxDB) wrapTx(tx *sql.Tx) txMethods {
	return &pgxTx{
		dialectTx: dialectTx{tx: tx},
		pgxImpl: &pgxImpl{
			db:     obj.db,
			driver: tx,
			txn:    true,
		},
	}
}

type pgxTx struct {
	dialectTx
	*pgxImpl
}

func pgxLogStmt(stmt string, args ...any) {
	// TODO: render placeholders
	if Logger != nil {
		out := fmt.Sprintf("stmt: %s\nargs: %v\n", stmt, pretty(args))
		Logger(out)
	}
}

type pgxcockroachImpl struct {
	db      *DB
	dialect __sqlbundle_pgxcockroach
	driver  driver
	txn     bool
}

func (obj *pgxcockroachImpl) Rebind(s string) string {
	return obj.dialect.Rebind(s)
}

func (obj *pgxcockroachImpl) logStmt(stmt string, args ...any) {
	pgxcockroachLogStmt(stmt, args...)
}

func (obj *pgxcockroachImpl) makeErr(err error) error {
	constraint, ok := obj.isConstraintError(err)
	if ok {
		return constraintViolation(err, constraint)
	}
	return makeErr(err)
}

type pgxcockroachDB struct {
	db *DB
	*pgxcockroachImpl
}

func newpgxcockroach(db *DB) *pgxcockroachDB {
	return &pgxcockroachDB{
		db: db,
		pgxcockroachImpl: &pgxcockroachImpl{
			db:     db,
			driver: db.DB,
		},
	}
}

func (obj *pgxcockroachDB) Schema() []string {
	return []string{

		`CREATE TABLE people (
	pk bigserial NOT NULL,
	name text NOT NULL,
	u64 bigint NOT NULL,
	u64_up bigint NOT NULL,
	u64_null bigint,
	u64_null_up bigint,
	PRIMARY KEY ( pk )
)`,
	}
}

func (obj *pgxcockroachDB) DropSchema() []string {
	return []string{

		`DROP TABLE IF EXISTS people`,
	}
}

func (obj *pgxcockroachDB) wrapTx(tx *sql.Tx) txMethods {
	return &pgxcockroachTx{
		dialectTx: dialectTx{tx: tx},
		pgxcockroachImpl: &pgxcockroachImpl{
			db:     obj.db,
			driver: tx,
			txn:    true,
		},
	}
}

type pgxcockroachTx struct {
	dialectTx
	*pgxcockroachImpl
}

func pgxcockroachLogStmt(stmt string, args ...any) {
	// TODO: render placeholders
	if Logger != nil {
		out := fmt.Sprintf("stmt: %s\nargs: %v\n", stmt, pretty(args))
		Logger(out)
	}
}

type spannerImpl struct {
	db      *DB
	dialect __sqlbundle_spanner
	driver  driver
	txn     bool
}

func (obj *spannerImpl) Rebind(s string) string {
	return obj.dialect.Rebind(s)
}

func (obj *spannerImpl) logStmt(stmt string, args ...any) {
	spannerLogStmt(stmt, args...)
}

func (obj *spannerImpl) makeErr(err error) error {
	constraint, ok := obj.isConstraintError(err)
	if ok {
		return constraintViolation(err, constraint)
	}
	return makeErr(err)
}

type spannerDB struct {
	db *DB
	*spannerImpl
}

func newspanner(db *DB) *spannerDB {
	return &spannerDB{
		db: db,
		spannerImpl: &spannerImpl{
			db:     db,
			driver: db.DB,
		},
	}
}

func (obj *spannerDB) Schema() []string {
	return []string{

		`CREATE SEQUENCE people_pk OPTIONS (sequence_kind='bit_reversed_positive')`,

		`CREATE TABLE people (
	pk INT64 NOT NULL DEFAULT (GET_NEXT_SEQUENCE_VALUE(SEQUENCE people_pk)),
	name STRING(MAX) NOT NULL,
	u64 INT64 NOT NULL,
	u64_up INT64 NOT NULL,
	u64_null INT64,
	u64_null_up INT64
) PRIMARY KEY ( pk )`,
	}
}

func (obj *spannerDB) DropSchema() []string {
	return []string{

		`ALTER TABLE  people ALTER pk SET DEFAULT (null)`,

		`DROP SEQUENCE IF EXISTS people_pk`,

		`DROP TABLE IF EXISTS people`,
	}
}

func (obj *spannerDB) wrapTx(tx *sql.Tx) txMethods {
	return &spannerTx{
		dialectTx: dialectTx{tx: tx},
		spannerImpl: &spannerImpl{
			db:     obj.db,
			driver: tx,
			txn:    true,
		},
	}
}

type spannerTx struct {
	dialectTx
	*spannerImpl
}

func spannerLogStmt(stmt string, args ...any) {
	// TODO: render placeholders
	if Logger != nil {
		out := fmt.Sprintf("stmt: %s\nargs: %v\n", stmt, pretty(args))
		Logger(out)
	}
}

type pretty []any

func (p pretty) Format(f fmt.State, c rune) {
	fmt.Fprint(f, "[")
nextval:
	for i, val := range p {
		if i > 0 {
			fmt.Fprint(f, ", ")
		}
		rv := reflect.ValueOf(val)
		if rv.Kind() == reflect.Ptr {
			if rv.IsNil() {
				fmt.Fprint(f, "NULL")
				continue
			}
			val = rv.Elem().Interface()
		}
		switch v := val.(type) {
		case string:
			fmt.Fprintf(f, "%q", v)
		case time.Time:
			fmt.Fprintf(f, "%s", v.Format(time.RFC3339Nano))
		case []byte:
			for _, b := range v {
				if !unicode.IsPrint(rune(b)) {
					fmt.Fprintf(f, "%#x", v)
					continue nextval
				}
			}
			fmt.Fprintf(f, "%q", v)
		default:
			fmt.Fprintf(f, "%v", v)
		}
	}
	fmt.Fprint(f, "]")
}

type Person struct {
	Pk        int64
	Name      string
	U64       uint64
	U64Up     uint64
	U64Null   *uint64
	U64NullUp *uint64
}

func (Person) _Table() string { return "people" }

type Person_Create_Fields struct {
	U64Null   Person_U64Null_Field
	U64NullUp Person_U64NullUp_Field
}

type Person_Update_Fields struct {
	U64Up     Person_U64Up_Field
	U64NullUp Person_U64NullUp_Field
}

type Person_Pk_Field struct {
	_set   bool
	_null  bool
	_value int64
}

func Person_Pk(v int64) Person_Pk_Field {
	return Person_Pk_Field{_set: true, _value: v}
}

func (f Person_Pk_Field) value() any {
	if !f._set || f._null {
		return nil
	}
	return f._value
}

type Person_Name_Field struct {
	_set   bool
	_null  bool
	_value string
}

func Person_Name(v string) Person_Name_Field {
	return Person_Name_Field{_set: true, _value: v}
}

func (f Person_Name_Field) value() any {
	if !f._set || f._null {
		return nil
	}
	return f._value
}

type Person_U64_Field struct {
	_set   bool
	_null  bool
	_value uint64
}

func Person_U64(v uint64) Person_U64_Field {
	return Person_U64_Field{_set: true, _value: v}
}

func (f Person_U64_Field) value() any {
	if !f._set || f._null {
		return nil
	}
	return f._value
}

type Person_U64Up_Field struct {
	_set   bool
	_null  bool
	_value uint64
}

func Person_U64Up(v uint64) Person_U64Up_Field {
	return Person_U64Up_Field{_set: true, _value: v}
}

func (f Person_U64Up_Field) value() any {
	if !f._set || f._null {
		return nil
	}
	return f._value
}

type Person_U64Null_Field struct {
	_set   bool
	_null  bool
	_value *uint64
}

func Person_U64Null(v uint64) Person_U64Null_Field {
	return Person_U64Null_Field{_set: true, _value: &v}
}

func Person_U64Null_Raw(v *uint64) Person_U64Null_Field {
	if v == nil {
		return Person_U64Null_Null()
	}
	return Person_U64Null(*v)
}

func Person_U64Null_Null() Person_U64Null_Field {
	return Person_U64Null_Field{_set: true, _null: true}
}

func (f Person_U64Null_Field) isnull() bool { return !f._set || f._null || f._value == nil }

func (f Person_U64Null_Field) value() any {
	if !f._set || f._null {
		return nil
	}
	return f._value
}

type Person_U64NullUp_Field struct {
	_set   bool
	_null  bool
	_value *uint64
}

func Person_U64NullUp(v uint64) Person_U64NullUp_Field {
	return Person_U64NullUp_Field{_set: true, _value: &v}
}

func Person_U64NullUp_Raw(v *uint64) Person_U64NullUp_Field {
	if v == nil {
		return Person_U64NullUp_Null()
	}
	return Person_U64NullUp(*v)
}

func Person_U64NullUp_Null() Person_U64NullUp_Field {
	return Person_U64NullUp_Field{_set: true, _null: true}
}

func (f Person_U64NullUp_Field) isnull() bool { return !f._set || f._null || f._value == nil }

func (f Person_U64NullUp_Field) value() any {
	if !f._set || f._null {
		return nil
	}
	return f._value
}

func toUTC(t time.Time) time.Time {
	return t.UTC()
}

func toDate(t time.Time) time.Time {
	// keep up the minute portion so that translations between timezones will
	// continue to reflect properly.
	return t.Truncate(time.Minute)
}

//
// runtime support for building sql statements
//

type __sqlbundle_SQL interface {
	Render() string

	private()
}

type __sqlbundle_Dialect interface {
	// Rebind gives the opportunity to rewrite provided SQL into a SQL dialect.
	Rebind(sql string) string
}

type __sqlbundle_RenderOp int

const (
	__sqlbundle_NoFlatten __sqlbundle_RenderOp = iota
	__sqlbundle_NoTerminate
)

func __sqlbundle_RenderAll(dialect __sqlbundle_Dialect, sqls []__sqlbundle_SQL, ops ...__sqlbundle_RenderOp) []string {
	var rs []string
	for _, sql := range sqls {
		rs = append(rs, __sqlbundle_Render(dialect, sql, ops...))
	}
	return rs
}

func __sqlbundle_Render(dialect __sqlbundle_Dialect, sql __sqlbundle_SQL, ops ...__sqlbundle_RenderOp) string {
	out := sql.Render()

	flatten := true
	terminate := true
	for _, op := range ops {
		switch op {
		case __sqlbundle_NoFlatten:
			flatten = false
		case __sqlbundle_NoTerminate:
			terminate = false
		}
	}

	if flatten {
		out = __sqlbundle_flattenSQL(out)
	}
	if terminate {
		out += ";"
	}

	return dialect.Rebind(out)
}

func __sqlbundle_flattenSQL(x string) string {
	// trim whitespace from beginning and end
	s, e := 0, len(x)-1
	for s < len(x) && (x[s] == ' ' || x[s] == '\t' || x[s] == '\n') {
		s++
	}
	for s <= e && (x[e] == ' ' || x[e] == '\t' || x[e] == '\n') {
		e--
	}
	if s > e {
		return ""
	}
	x = x[s : e+1]

	// check for whitespace that needs fixing
	wasSpace := false
	for i := 0; i < len(x); i++ {
		r := x[i]
		justSpace := r == ' '
		if (wasSpace && justSpace) || r == '\t' || r == '\n' {
			// whitespace detected, start writing a new string
			var result strings.Builder
			result.Grow(len(x))
			if wasSpace {
				result.WriteString(x[:i-1])
			} else {
				result.WriteString(x[:i])
			}
			for p := i; p < len(x); p++ {
				for p < len(x) && (x[p] == ' ' || x[p] == '\t' || x[p] == '\n') {
					p++
				}
				result.WriteByte(' ')

				start := p
				for p < len(x) && !(x[p] == ' ' || x[p] == '\t' || x[p] == '\n') {
					p++
				}
				result.WriteString(x[start:p])
			}

			return result.String()
		}
		wasSpace = justSpace
	}

	// no problematic whitespace found
	return x
}

// this type is specially named to match up with the name returned by the
// dialect impl in the sql package.
type __sqlbundle_cockroach struct{}

func (p __sqlbundle_cockroach) Rebind(sql string) string {
	return __sqlbundle_postgres{}.Rebind(sql)
}

// this type is specially named to match up with the name returned by the
// dialect impl in the sql package.
type __sqlbundle_pgx struct{}

func (p __sqlbundle_pgx) Rebind(sql string) string {
	return __sqlbundle_postgres{}.Rebind(sql)
}

// this type is specially named to match up with the name returned by the
// dialect impl in the sql package.
type __sqlbundle_pgxcockroach struct{}

func (p __sqlbundle_pgxcockroach) Rebind(sql string) string {
	return __sqlbundle_postgres{}.Rebind(sql)
}

// this type is specially named to match up with the name returned by the
// dialect impl in the sql package.
type __sqlbundle_postgres struct{}

func (p __sqlbundle_postgres) Rebind(sql string) string {
	type sqlParseState int
	const (
		sqlParseStart sqlParseState = iota
		sqlParseInStringLiteral
		sqlParseInQuotedIdentifier
		sqlParseInComment
	)

	out := make([]byte, 0, len(sql)+10)

	j := 1
	state := sqlParseStart
	for i := 0; i < len(sql); i++ {
		ch := sql[i]
		switch state {
		case sqlParseStart:
			switch ch {
			case '?':
				out = append(out, '$')
				out = append(out, strconv.Itoa(j)...)
				state = sqlParseStart
				j++
				continue
			case '-':
				if i+1 < len(sql) && sql[i+1] == '-' {
					state = sqlParseInComment
				}
			case '"':
				state = sqlParseInQuotedIdentifier
			case '\'':
				state = sqlParseInStringLiteral
			}
		case sqlParseInStringLiteral:
			if ch == '\'' {
				state = sqlParseStart
			}
		case sqlParseInQuotedIdentifier:
			if ch == '"' {
				state = sqlParseStart
			}
		case sqlParseInComment:
			if ch == '\n' {
				state = sqlParseStart
			}
		}
		out = append(out, ch)
	}

	return string(out)
}

// this type is specially named to match up with the name returned by the
// dialect impl in the sql package.
type __sqlbundle_spanner struct{}

func (p __sqlbundle_spanner) Rebind(sql string) string {
	return sql
}

// this type is specially named to match up with the name returned by the
// dialect impl in the sql package.
type __sqlbundle_sqlite3 struct{}

func (s __sqlbundle_sqlite3) Rebind(sql string) string {
	return sql
}

type __sqlbundle_Literal string

func (__sqlbundle_Literal) private() {}

func (l __sqlbundle_Literal) Render() string { return string(l) }

type __sqlbundle_Literals struct {
	Join string
	SQLs []__sqlbundle_SQL
}

func (__sqlbundle_Literals) private() {}

func (l __sqlbundle_Literals) Render() string {
	var out bytes.Buffer

	first := true
	for _, sql := range l.SQLs {
		if sql == nil {
			continue
		}
		if !first {
			out.WriteString(l.Join)
		}
		first = false
		out.WriteString(sql.Render())
	}

	return out.String()
}

type __sqlbundle_Condition struct {
	// set at compile/embed time
	Name  string
	Left  string
	Equal bool
	Right string

	// set at runtime
	Null bool
}

func (*__sqlbundle_Condition) private() {}

func (c *__sqlbundle_Condition) Render() string {
	// TODO(jeff): maybe check if we can use placeholders instead of the
	// literal null: this would make the templates easier.

	switch {
	case c.Equal && c.Null:
		return c.Left + " is null"
	case c.Equal && !c.Null:
		return c.Left + " = " + c.Right
	case !c.Equal && c.Null:
		return c.Left + " is not null"
	case !c.Equal && !c.Null:
		return c.Left + " != " + c.Right
	default:
		panic("unhandled case")
	}
}

type __sqlbundle_Hole struct {
	// set at compiile/embed time
	Name string

	// set at runtime or possibly embed time
	SQL __sqlbundle_SQL
}

func (*__sqlbundle_Hole) private() {}

func (h *__sqlbundle_Hole) Render() string {
	if h.SQL == nil {
		return ""
	}
	return h.SQL.Render()
}

//
// end runtime support for building sql statements
//

func (obj *sqlite3Impl) Create_Person(ctx context.Context,
	person_name Person_Name_Field,
	person_u64 Person_U64_Field,
	person_u64_up Person_U64Up_Field,
	optional Person_Create_Fields) (
	person *Person, err error) {
	__name_val := person_name.value()
	__u64_val := person_u64.value()
	__u64_up_val := person_u64_up.value()
	__u64_null_val := optional.U64Null.value()
	__u64_null_up_val := optional.U64NullUp.value()

	var __embed_stmt = __sqlbundle_Literal("INSERT INTO people ( name, u64, u64_up, u64_null, u64_null_up ) VALUES ( ?, ?, ?, ?, ? )")

	var __values []any
	__values = append(__values, __name_val, __u64_val, __u64_up_val, __u64_null_val, __u64_null_up_val)

	var __stmt = __sqlbundle_Render(obj.dialect, __embed_stmt)
	obj.logStmt(__stmt, __values...)

	__res, err := obj.driver.ExecContext(ctx, __stmt, __values...)
	if err != nil {
		return nil, obj.makeErr(err)
	}
	__pk, err := __res.LastInsertId()
	if err != nil {
		return nil, obj.makeErr(err)
	}
	return obj.getLastPerson(ctx, __pk)

}

func (obj *sqlite3Impl) Get_Person_By_Pk(ctx context.Context,
	person_pk Person_Pk_Field) (
	person *Person, err error) {

	var __embed_stmt = __sqlbundle_Literal("SELECT people.pk, people.name, people.u64, people.u64_up, people.u64_null, people.u64_null_up FROM people WHERE people.pk = ?")

	var __values []any
	__values = append(__values, person_pk.value())

	var __stmt = __sqlbundle_Render(obj.dialect, __embed_stmt)
	obj.logStmt(__stmt, __values...)

	person = &Person{}
	err = obj.driver.QueryRowContext(ctx, __stmt, __values...).Scan(&person.Pk, &person.Name, &person.U64, &person.U64Up, &person.U64Null, &person.U64NullUp)
	if err != nil {
		return (*Person)(nil), obj.makeErr(err)
	}
	return person, nil

}

func (obj *sqlite3Impl) Get_Person_By_U64_And_U64Up_And_U64Null_And_U64NullUp(ctx context.Context,
	person_u64 Person_U64_Field,
	person_u64_up Person_U64Up_Field,
	person_u64_null Person_U64Null_Field,
	person_u64_null_up Person_U64NullUp_Field) (
	person *Person, err error) {

	var __cond_0 = &__sqlbundle_Condition{Left: "people.u64_null", Equal: true, Right: "?", Null: true}
	var __cond_1 = &__sqlbundle_Condition{Left: "people.u64_null_up", Equal: true, Right: "?", Null: true}

	var __embed_stmt = __sqlbundle_Literals{Join: "", SQLs: []__sqlbundle_SQL{__sqlbundle_Literal("SELECT people.pk, people.name, people.u64, people.u64_up, people.u64_null, people.u64_null_up FROM people WHERE people.u64 = ? AND people.u64_up = ? AND "), __cond_0, __sqlbundle_Literal(" AND "), __cond_1, __sqlbundle_Literal(" LIMIT 2")}}

	var __values []any
	__values = append(__values, person_u64.value(), person_u64_up.value())
	if !person_u64_null.isnull() {
		__cond_0.Null = false
		__values = append(__values, person_u64_null.value())
	}
	if !person_u64_null_up.isnull() {
		__cond_1.Null = false
		__values = append(__values, person_u64_null_up.value())
	}

	var __stmt = __sqlbundle_Render(obj.dialect, __embed_stmt)
	obj.logStmt(__stmt, __values...)

	__rows, err := obj.driver.QueryContext(ctx, __stmt, __values...)
	if err != nil {
		return nil, obj.makeErr(err)
	}
	defer __rows.Close()

	if !__rows.Next() {
		if err := __rows.Err(); err != nil {
			return nil, obj.makeErr(err)
		}
		return nil, makeErr(sql.ErrNoRows)
	}

	person = &Person{}
	err = __rows.Scan(&person.Pk, &person.Name, &person.U64, &person.U64Up, &person.U64Null, &person.U64NullUp)
	if err != nil {
		return nil, obj.makeErr(err)
	}

	if __rows.Next() {
		return nil, tooManyRows("Person_By_U64_And_U64Up_And_U64Null_And_U64NullUp")
	}

	if err := __rows.Err(); err != nil {
		return nil, obj.makeErr(err)
	}

	return person, nil

}

func (obj *sqlite3Impl) Update_Person_By_Pk_And_U64_And_U64Up_And_U64Null_And_U64NullUp(ctx context.Context,
	person_pk Person_Pk_Field,
	person_u64 Person_U64_Field,
	person_u64_up Person_U64Up_Field,
	person_u64_null Person_U64Null_Field,
	person_u64_null_up Person_U64NullUp_Field,
	update Person_Update_Fields) (
	person *Person, err error) {

	var __sets = &__sqlbundle_Hole{}
	var __cond_0 = &__sqlbundle_Condition{Left: "people.u64_null", Equal: true, Right: "?", Null: true}
	var __cond_1 = &__sqlbundle_Condition{Left: "people.u64_null_up", Equal: true, Right: "?", Null: true}

	var __embed_stmt = __sqlbundle_Literals{Join: "", SQLs: []__sqlbundle_SQL{__sqlbundle_Literal("UPDATE people SET "), __sets, __sqlbundle_Literal(" WHERE people.pk = ? AND people.u64 = ? AND people.u64_up = ? AND "), __cond_0, __sqlbundle_Literal(" AND "), __cond_1}}

	__sets_sql := __sqlbundle_Literals{Join: ", "}
	var __values []any
	var __args []any

	if update.U64Up._set {
		__values = append(__values, update.U64Up.value())
		__sets_sql.SQLs = append(__sets_sql.SQLs, __sqlbundle_Literal("u64_up = ?"))
	}

	if update.U64NullUp._set {
		__values = append(__values, update.U64NullUp.value())
		__sets_sql.SQLs = append(__sets_sql.SQLs, __sqlbundle_Literal("u64_null_up = ?"))
	}

	if len(__sets_sql.SQLs) == 0 {
		return nil, emptyUpdate()
	}

	__args = append(__args, person_pk.value(), person_u64.value(), person_u64_up.value())
	if !person_u64_null.isnull() {
		__cond_0.Null = false
		__args = append(__args, person_u64_null.value())
	}
	if !person_u64_null_up.isnull() {
		__cond_1.Null = false
		__args = append(__args, person_u64_null_up.value())
	}

	__values = append(__values, __args...)
	__sets.SQL = __sets_sql

	var __stmt = __sqlbundle_Render(obj.dialect, __embed_stmt)
	obj.logStmt(__stmt, __values...)

	person = &Person{}
	_, err = obj.driver.ExecContext(ctx, __stmt, __values...)
	if err != nil {
		return nil, obj.makeErr(err)
	}

	var __embed_stmt_get = __sqlbundle_Literals{Join: "", SQLs: []__sqlbundle_SQL{__sqlbundle_Literal("SELECT people.pk, people.name, people.u64, people.u64_up, people.u64_null, people.u64_null_up FROM people WHERE people.pk = ? AND people.u64 = ? AND people.u64_up = ? AND "), __cond_0, __sqlbundle_Literal(" AND "), __cond_1}}

	var __stmt_get = __sqlbundle_Render(obj.dialect, __embed_stmt_get)
	obj.logStmt("(IMPLIED) "+__stmt_get, __args...)

	err = obj.driver.QueryRowContext(ctx, __stmt_get, __args...).Scan(&person.Pk, &person.Name, &person.U64, &person.U64Up, &person.U64Null, &person.U64NullUp)
	if err == sql.ErrNoRows {
		return nil, nil
	}
	if err != nil {
		return nil, obj.makeErr(err)
	}
	return person, nil
}

func (obj *sqlite3Impl) Delete_Person_By_U64_And_U64Up_And_U64Null_And_U64NullUp(ctx context.Context,
	person_u64 Person_U64_Field,
	person_u64_up Person_U64Up_Field,
	person_u64_null Person_U64Null_Field,
	person_u64_null_up Person_U64NullUp_Field) (
	count int64, err error) {

	var __cond_0 = &__sqlbundle_Condition{Left: "people.u64_null", Equal: true, Right: "?", Null: true}
	var __cond_1 = &__sqlbundle_Condition{Left: "people.u64_null_up", Equal: true, Right: "?", Null: true}

	var __embed_stmt = __sqlbundle_Literals{Join: "", SQLs: []__sqlbundle_SQL{__sqlbundle_Literal("DELETE FROM people WHERE people.u64 = ? AND people.u64_up = ? AND "), __cond_0, __sqlbundle_Literal(" AND "), __cond_1}}

	var __values []any
	__values = append(__values, person_u64.value(), person_u64_up.value())
	if !person_u64_null.isnull() {
		__cond_0.Null = false
		__values = append(__values, person_u64_null.value())
	}
	if !person_u64_null_up.isnull() {
		__cond_1.Null = false
		__values = append(__values, person_u64_null_up.value())
	}

	var __stmt = __sqlbundle_Render(obj.dialect, __embed_stmt)
	obj.logStmt(__stmt, __values...)

	__res, err := obj.driver.ExecContext(ctx, __stmt, __values...)
	if err != nil {
		return 0, obj.makeErr(err)
	}

	count, err = __res.RowsAffected()
	if err != nil {
		return 0, obj.makeErr(err)
	}

	return count, nil

}

func (obj *sqlite3Impl) getLastPerson(ctx context.Context,
	pk int64) (
	person *Person, err error) {

	var __embed_stmt = __sqlbundle_Literal("SELECT people.pk, people.name, people.u64, people.u64_up, people.u64_null, people.u64_null_up FROM people WHERE _rowid_ = ?")

	var __stmt = __sqlbundle_Render(obj.dialect, __embed_stmt)
	obj.logStmt(__stmt, pk)

	person = &Person{}
	err = obj.driver.QueryRowContext(ctx, __stmt, pk).Scan(&person.Pk, &person.Name, &person.U64, &person.U64Up, &person.U64Null, &person.U64NullUp)
	if err != nil {
		return (*Person)(nil), obj.makeErr(err)
	}
	return person, nil

}

func (impl sqlite3Impl) isConstraintError(err error) (constraint string, ok bool) {
	if e, ok := err.(sqlite3.Error); ok {
		if e.Code == sqlite3.ErrConstraint {
			msg := err.Error()
			colon := strings.LastIndex(msg, ":")
			if colon != -1 {
				return strings.TrimSpace(msg[colon:]), true
			}
			return "", true
		}
	}
	return "", false
}

func (obj *sqlite3Impl) deleteAll(ctx context.Context) (count int64, err error) {
	var __res sql.Result
	var __count int64
	__res, err = obj.driver.ExecContext(ctx, "DELETE FROM people;")
	if err != nil {
		return 0, obj.makeErr(err)
	}

	__count, err = __res.RowsAffected()
	if err != nil {
		return 0, obj.makeErr(err)
	}
	count += __count

	return count, nil

}

func (obj *pgxImpl) Create_Person(ctx context.Context,
	person_name Person_Name_Field,
	person_u64 Person_U64_Field,
	person_u64_up Person_U64Up_Field,
	optional Person_Create_Fields) (
	person *Person, err error) {
	__name_val := person_name.value()
	__u64_val := person_u64.value()
	__u64_up_val := person_u64_up.value()
	__u64_null_val := optional.U64Null.value()
	__u64_null_up_val := optional.U64NullUp.value()

	var __embed_stmt = __sqlbundle_Literal("INSERT INTO people ( name, u64, u64_up, u64_null, u64_null_up ) VALUES ( ?, ?, ?, ?, ? ) RETURNING people.pk, people.name, people.u64, people.u64_up, people.u64_null, people.u64_null_up")

	var __values []any
	__values = append(__values, __name_val, __u64_val, __u64_up_val, __u64_null_val, __u64_null_up_val)

	var __stmt = __sqlbundle_Render(obj.dialect, __embed_stmt)
	obj.logStmt(__stmt, __values...)

	person = &Person{}
	err = obj.driver.QueryRowContext(ctx, __stmt, __values...).Scan(&person.Pk, &person.Name, &person.U64, &person.U64Up, &person.U64Null, &person.U64NullUp)
	if err != nil {
		return nil, obj.makeErr(err)
	}
	return person, nil

}

func (obj *pgxImpl) Get_Person_By_Pk(ctx context.Context,
	person_pk Person_Pk_Field) (
	person *Person, err error) {

	var __embed_stmt = __sqlbundle_Literal("SELECT people.pk, people.name, people.u64, people.u64_up, people.u64_null, people.u64_null_up FROM people WHERE people.pk = ?")

	var __values []any
	__values = append(__values, person_pk.value())

	var __stmt = __sqlbundle_Render(obj.dialect, __embed_stmt)
	obj.logStmt(__stmt, __values...)

	person = &Person{}
	err = obj.driver.QueryRowContext(ctx, __stmt, __values...).Scan(&person.Pk, &person.Name, &person.U64, &person.U64Up, &person.U64Null, &person.U64NullUp)
	if err != nil {
		return (*Person)(nil), obj.makeErr(err)
	}
	return person, nil

}

func (obj *pgxImpl) Get_Person_By_U64_And_U64Up_And_U64Null_And_U64NullUp(ctx context.Context,
	person_u64 Person_U64_Field,
	person_u64_up Person_U64Up_Field,
	person_u64_null Person_U64Null_Field,
	person_u64_null_up Person_U64NullUp_Field) (
	person *Person, err error) {

	var __cond_0 = &__sqlbundle_Condition{Left: "people.u64_null", Equal: true, Right: "?", Null: true}
	var __cond_1 = &__sqlbundle_Condition{Left: "people.u64_null_up", Equal: true, Right: "?", Null: true}

	var __embed_stmt = __sqlbundle_Literals{Join: "", SQLs: []__sqlbundle_SQL{__sqlbundle_Literal("SELECT people.pk, people.name, people.u64, people.u64_up, people.u64_null, people.u64_null_up FROM people WHERE people.u64 = ? AND people.u64_up = ? AND "), __cond_0, __sqlbundle_Literal(" AND "), __cond_1, __sqlbundle_Literal(" LIMIT 2")}}

	var __values []any
	__values = append(__values, person_u64.value(), person_u64_up.value())
	if !person_u64_null.isnull() {
		__cond_0.Null = false
		__values = append(__values, person_u64_null.value())
	}
	if !person_u64_null_up.isnull() {
		__cond_1.Null = false
		__values = append(__values, person_u64_null_up.value())
	}

	var __stmt = __sqlbundle_Render(obj.dialect, __embed_stmt)
	obj.logStmt(__stmt, __values...)

	__rows, err := obj.driver.QueryContext(ctx, __stmt, __values...)
	if err != nil {
		return nil, obj.makeErr(err)
	}
	defer __rows.Close()

	if !__rows.Next() {
		if err := __rows.Err(); err != nil {
			return nil, obj.makeErr(err)
		}
		return nil, makeErr(sql.ErrNoRows)
	}

	person = &Person{}
	err = __rows.Scan(&person.Pk, &person.Name, &person.U64, &person.U64Up, &person.U64Null, &person.U64NullUp)
	if err != nil {
		return nil, obj.makeErr(err)
	}

	if __rows.Next() {
		return nil, tooManyRows("Person_By_U64_And_U64Up_And_U64Null_And_U64NullUp")
	}

	if err := __rows.Err(); err != nil {
		return nil, obj.makeErr(err)
	}

	return person, nil

}

func (obj *pgxImpl) Update_Person_By_Pk_And_U64_And_U64Up_And_U64Null_And_U64NullUp(ctx context.Context,
	person_pk Person_Pk_Field,
	person_u64 Person_U64_Field,
	person_u64_up Person_U64Up_Field,
	person_u64_null Person_U64Null_Field,
	person_u64_null_up Person_U64NullUp_Field,
	update Person_Update_Fields) (
	person *Person, err error) {

	var __sets = &__sqlbundle_Hole{}
	var __cond_0 = &__sqlbundle_Condition{Left: "people.u64_null", Equal: true, Right: "?", Null: true}
	var __cond_1 = &__sqlbundle_Condition{Left: "people.u64_null_up", Equal: true, Right: "?", Null: true}

	var __embed_stmt = __sqlbundle_Literals{Join: "", SQLs: []__sqlbundle_SQL{__sqlbundle_Literal("UPDATE people SET "), __sets, __sqlbundle_Literal(" WHERE people.pk = ? AND people.u64 = ? AND people.u64_up = ? AND "), __cond_0, __sqlbundle_Literal(" AND "), __cond_1, __sqlbundle_Literal(" RETURNING people.pk, people.name, people.u64, people.u64_up, people.u64_null, people.u64_null_up")}}

	__sets_sql := __sqlbundle_Literals{Join: ", "}
	var __values []any
	var __args []any

	if update.U64Up._set {
		__values = append(__values, update.U64Up.value())
		__sets_sql.SQLs = append(__sets_sql.SQLs, __sqlbundle_Literal("u64_up = ?"))
	}

	if update.U64NullUp._set {
		__values = append(__values, update.U64NullUp.value())
		__sets_sql.SQLs = append(__sets_sql.SQLs, __sqlbundle_Literal("u64_null_up = ?"))
	}

	if len(__sets_sql.SQLs) == 0 {
		return nil, emptyUpdate()
	}

	__args = append(__args, person_pk.value(), person_u64.value(), person_u64_up.value())
	if !person_u64_null.isnull() {
		__cond_0.Null = false
		__args = append(__args, person_u64_null.value())
	}
	if !person_u64_null_up.isnull() {
		__cond_1.Null = false
		__args = append(__args, person_u64_null_up.value())
	}

	__values = append(__values, __args...)
	__sets.SQL = __sets_sql

	var __stmt = __sqlbundle_Render(obj.dialect, __embed_stmt)
	obj.logStmt(__stmt, __values...)

	person = &Person{}
	err = obj.driver.QueryRowContext(ctx, __stmt, __values...).Scan(&person.Pk, &person.Name, &person.U64, &person.U64Up, &person.U64Null, &person.U64NullUp)
	if err == sql.ErrNoRows {
		return nil, nil
	}
	if err != nil {
		return nil, obj.makeErr(err)
	}
	return person, nil
}

func (obj *pgxImpl) Delete_Person_By_U64_And_U64Up_And_U64Null_And_U64NullUp(ctx context.Context,
	person_u64 Person_U64_Field,
	person_u64_up Person_U64Up_Field,
	person_u64_null Person_U64Null_Field,
	person_u64_null_up Person_U64NullUp_Field) (
	count int64, err error) {

	var __cond_0 = &__sqlbundle_Condition{Left: "people.u64_null", Equal: true, Right: "?", Null: true}
	var __cond_1 = &__sqlbundle_Condition{Left: "people.u64_null_up", Equal: true, Right: "?", Null: true}

	var __embed_stmt = __sqlbundle_Literals{Join: "", SQLs: []__sqlbundle_SQL{__sqlbundle_Literal("DELETE FROM people WHERE people.u64 = ? AND people.u64_up = ? AND "), __cond_0, __sqlbundle_Literal(" AND "), __cond_1}}

	var __values []any
	__values = append(__values, person_u64.value(), person_u64_up.value())
	if !person_u64_null.isnull() {
		__cond_0.Null = false
		__values = append(__values, person_u64_null.value())
	}
	if !person_u64_null_up.isnull() {
		__cond_1.Null = false
		__values = append(__values, person_u64_null_up.value())
	}

	var __stmt = __sqlbundle_Render(obj.dialect, __embed_stmt)
	obj.logStmt(__stmt, __values...)

	__res, err := obj.driver.ExecContext(ctx, __stmt, __values...)
	if err != nil {
		return 0, obj.makeErr(err)
	}

	count, err = __res.RowsAffected()
	if err != nil {
		return 0, obj.makeErr(err)
	}

	return count, nil

}

func (impl pgxImpl) isConstraintError(err error) (constraint string, ok bool) {
	if e, ok := err.(*pgconn.PgError); ok {
		if e.Code[:2] == "23" {
			return e.ConstraintName, true
		}
	}
	return "", false
}

func (obj *pgxImpl) deleteAll(ctx context.Context) (count int64, err error) {
	var __res sql.Result
	var __count int64
	__res, err = obj.driver.ExecContext(ctx, "DELETE FROM people;")
	if err != nil {
		return 0, obj.makeErr(err)
	}

	__count, err = __res.RowsAffected()
	if err != nil {
		return 0, obj.makeErr(err)
	}
	count += __count

	return count, nil

}

func (obj *pgxcockroachImpl) Create_Person(ctx context.Context,
	person_name Person_Name_Field,
	person_u64 Person_U64_Field,
	person_u64_up Person_U64Up_Field,
	optional Person_Create_Fields) (
	person *Person, err error) {
	__name_val := person_name.value()
	__u64_val := person_u64.value()
	__u64_up_val := person_u64_up.value()
	__u64_null_val := optional.U64Null.value()
	__u64_null_up_val := optional.U64NullUp.value()

	var __embed_stmt = __sqlbundle_Literal("INSERT INTO people ( name, u64, u64_up, u64_null, u64_null_up ) VALUES ( ?, ?, ?, ?, ? ) RETURNING people.pk, people.name, people.u64, people.u64_up, people.u64_null, people.u64_null_up")

	var __values []any
	__values = append(__values, __name_val, __u64_val, __u64_up_val, __u64_null_val, __u64_null_up_val)

	var __stmt = __sqlbundle_Render(obj.dialect, __embed_stmt)
	obj.logStmt(__stmt, __values...)

	person = &Person{}
	err = obj.driver.QueryRowContext(ctx, __stmt, __values...).Scan(&person.Pk, &person.Name, &person.U64, &person.U64Up, &person.U64Null, &person.U64NullUp)
	if err != nil {
		return nil, obj.makeErr(err)
	}
	return person, nil

}

func (obj *pgxcockroachImpl) Get_Person_By_Pk(ctx context.Context,
	person_pk Person_Pk_Field) (
	person *Person, err error) {

	var __embed_stmt = __sqlbundle_Literal("SELECT people.pk, people.name, people.u64, people.u64_up, people.u64_null, people.u64_null_up FROM people WHERE people.pk = ?")

	var __values []any
	__values = append(__values, person_pk.value())

	var __stmt = __sqlbundle_Render(obj.dialect, __embed_stmt)
	obj.logStmt(__stmt, __values...)

	person = &Person{}
	err = obj.driver.QueryRowContext(ctx, __stmt, __values...).Scan(&person.Pk, &person.Name, &person.U64, &person.U64Up, &person.U64Null, &person.U64NullUp)
	if err != nil {
		return (*Person)(nil), obj.makeErr(err)
	}
	return person, nil

}

func (obj *pgxcockroachImpl) Get_Person_By_U64_And_U64Up_And_U64Null_And_U64NullUp(ctx context.Context,
	person_u64 Person_U64_Field,
	person_u64_up Person_U64Up_Field,
	person_u64_null Person_U64Null_Field,
	person_u64_null_up Person_U64NullUp_Field) (
	person *Person, err error) {

	var __cond_0 = &__sqlbundle_Condition{Left: "people.u64_null", Equal: true, Right: "?", Null: true}
	var __cond_1 = &__sqlbundle_Condition{Left: "people.u64_null_up", Equal: true, Right: "?", Null: true}

	var __embed_stmt = __sqlbundle_Literals{Join: "", SQLs: []__sqlbundle_SQL{__sqlbundle_Literal("SELECT people.pk, people.name, people.u64, people.u64_up, people.u64_null, people.u64_null_up FROM people WHERE people.u64 = ? AND people.u64_up = ? AND "), __cond_0, __sqlbundle_Literal(" AND "), __cond_1, __sqlbundle_Literal(" LIMIT 2")}}

	var __values []any
	__values = append(__values, person_u64.value(), person_u64_up.value())
	if !person_u64_null.isnull() {
		__cond_0.Null = false
		__values = append(__values, person_u64_null.value())
	}
	if !person_u64_null_up.isnull() {
		__cond_1.Null = false
		__values = append(__values, person_u64_null_up.value())
	}

	var __stmt = __sqlbundle_Render(obj.dialect, __embed_stmt)
	obj.logStmt(__stmt, __values...)

	__rows, err := obj.driver.QueryContext(ctx, __stmt, __values...)
	if err != nil {
		return nil, obj.makeErr(err)
	}
	defer __rows.Close()

	if !__rows.Next() {
		if err := __rows.Err(); err != nil {
			return nil, obj.makeErr(err)
		}
		return nil, makeErr(sql.ErrNoRows)
	}

	person = &Person{}
	err = __rows.Scan(&person.Pk, &person.Name, &person.U64, &person.U64Up, &person.U64Null, &person.U64NullUp)
	if err != nil {
		return nil, obj.makeErr(err)
	}

	if __rows.Next() {
		return nil, tooManyRows("Person_By_U64_And_U64Up_And_U64Null_And_U64NullUp")
	}

	if err := __rows.Err(); err != nil {
		return nil, obj.makeErr(err)
	}

	return person, nil

}

func (obj *pgxcockroachImpl) Update_Person_By_Pk_And_U64_And_U64Up_And_U64Null_And_U64NullUp(ctx context.Context,
	person_pk Person_Pk_Field,
	person_u64 Person_U64_Field,
	person_u64_up Person_U64Up_Field,
	person_u64_null Person_U64Null_Field,
	person_u64_null_up Person_U64NullUp_Field,
	update Person_Update_Fields) (
	person *Person, err error) {

	var __sets = &__sqlbundle_Hole{}
	var __cond_0 = &__sqlbundle_Condition{Left: "people.u64_null", Equal: true, Right: "?", Null: true}
	var __cond_1 = &__sqlbundle_Condition{Left: "people.u64_null_up", Equal: true, Right: "?", Null: true}

	var __embed_stmt = __sqlbundle_Literals{Join: "", SQLs: []__sqlbundle_SQL{__sqlbundle_Literal("UPDATE people SET "), __sets, __sqlbundle_Literal(" WHERE people.pk = ? AND people.u64 = ? AND people.u64_up = ? AND "), __cond_0, __sqlbundle_Literal(" AND "), __cond_1, __sqlbundle_Literal(" RETURNING people.pk, people.name, people.u64, people.u64_up, people.u64_null, people.u64_null_up")}}

	__sets_sql := __sqlbundle_Literals{Join: ", "}
	var __values []any
	var __args []any

	if update.U64Up._set {
		__values = append(__values, update.U64Up.value())
		__sets_sql.SQLs = append(__sets_sql.SQLs, __sqlbundle_Literal("u64_up = ?"))
	}

	if update.U64NullUp._set {
		__values = append(__values, update.U64NullUp.value())
		__sets_sql.SQLs = append(__sets_sql.SQLs, __sqlbundle_Literal("u64_null_up = ?"))
	}

	if len(__sets_sql.SQLs) == 0 {
		return nil, emptyUpdate()
	}

	__args = append(__args, person_pk.value(), person_u64.value(), person_u64_up.value())
	if !person_u64_null.isnull() {
		__cond_0.Null = false
		__args = append(__args, person_u64_null.value())
	}
	if !person_u64_null_up.isnull() {
		__cond_1.Null = false
		__args = append(__args, person_u64_null_up.value())
	}

	__values = append(__values, __args...)
	__sets.SQL = __sets_sql

	var __stmt = __sqlbundle_Render(obj.dialect, __embed_stmt)
	obj.logStmt(__stmt, __values...)

	person = &Person{}
	err = obj.driver.QueryRowContext(ctx, __stmt, __values...).Scan(&person.Pk, &person.Name, &person.U64, &person.U64Up, &person.U64Null, &person.U64NullUp)
	if err == sql.ErrNoRows {
		return nil, nil
	}
	if err != nil {
		return nil, obj.makeErr(err)
	}
	return person, nil
}

func (obj *pgxcockroachImpl) Delete_Person_By_U64_And_U64Up_And_U64Null_And_U64NullUp(ctx context.Context,
	person_u64 Person_U64_Field,
	person_u64_up Person_U64Up_Field,
	person_u64_null Person_U64Null_Field,
	person_u64_null_up Person_U64NullUp_Field) (
	count int64, err error) {

	var __cond_0 = &__sqlbundle_Condition{Left: "people.u64_null", Equal: true, Right: "?", Null: true}
	var __cond_1 = &__sqlbundle_Condition{Left: "people.u64_null_up", Equal: true, Right: "?", Null: true}

	var __embed_stmt = __sqlbundle_Literals{Join: "", SQLs: []__sqlbundle_SQL{__sqlbundle_Literal("DELETE FROM people WHERE people.u64 = ? AND people.u64_up = ? AND "), __cond_0, __sqlbundle_Literal(" AND "), __cond_1}}

	var __values []any
	__values = append(__values, person_u64.value(), person_u64_up.value())
	if !person_u64_null.isnull() {
		__cond_0.Null = false
		__values = append(__values, person_u64_null.value())
	}
	if !person_u64_null_up.isnull() {
		__cond_1.Null = false
		__values = append(__values, person_u64_null_up.value())
	}

	var __stmt = __sqlbundle_Render(obj.dialect, __embed_stmt)
	obj.logStmt(__stmt, __values...)

	__res, err := obj.driver.ExecContext(ctx, __stmt, __values...)
	if err != nil {
		return 0, obj.makeErr(err)
	}

	count, err = __res.RowsAffected()
	if err != nil {
		return 0, obj.makeErr(err)
	}

	return count, nil

}

func (impl pgxcockroachImpl) isConstraintError(err error) (constraint string, ok bool) {
	if e, ok := err.(*pgconn.PgError); ok {
		if e.Code[:2] == "23" {
			return e.ConstraintName, true
		}
	}
	return "", false
}

func (obj *pgxcockroachImpl) deleteAll(ctx context.Context) (count int64, err error) {
	var __res sql.Result
	var __count int64
	__res, err = obj.driver.ExecContext(ctx, "DELETE FROM people;")
	if err != nil {
		return 0, obj.makeErr(err)
	}

	__count, err = __res.RowsAffected()
	if err != nil {
		return 0, obj.makeErr(err)
	}
	count += __count

	return count, nil

}

func (obj *spannerImpl) Create_Person(ctx context.Context,
	person_name Person_Name_Field,
	person_u64 Person_U64_Field,
	person_u64_up Person_U64Up_Field,
	optional Person_Create_Fields) (
	person *Person, err error) {
	__name_val := person_name.value()
	__u64_val := spannerConvertArgument(person_u64.value())
	__u64_up_val := spannerConvertArgument(person_u64_up.value())
	__u64_null_val := spannerConvertArgument(optional.U64Null.value())
	__u64_null_up_val := spannerConvertArgument(optional.U64NullUp.value())

	var __embed_stmt = __sqlbundle_Literal("INSERT INTO people ( name, u64, u64_up, u64_null, u64_null_up ) VALUES ( ?, ?, ?, ?, ? ) THEN RETURN people.pk, people.name, people.u64, people.u64_up, people.u64_null, people.u64_null_up")

	var __values []any
	__values = append(__values, __name_val, __u64_val, __u64_up_val, __u64_null_val, __u64_null_up_val)

	var __stmt = __sqlbundle_Render(obj.dialect, __embed_stmt)
	obj.logStmt(__stmt, __values...)

	person = &Person{}
	d := obj.driver
	var tx *sql.Tx
	if !obj.txn {
		tx, err = obj.db.DB.BeginTx(ctx, nil)
		if err != nil {
			return nil, obj.makeErr(err)
		}
		d = tx
		defer func() {
			if txErr := tx.Rollback(); txErr != nil && !errors.Is(sql.ErrTxDone, txErr) {
				err = obj.makeErr(errors.Join(err, txErr))
			}
		}()
	}
	err = d.QueryRowContext(ctx, __stmt, __values...).Scan(&person.Pk, &person.Name, &person.U64, &person.U64Up, &person.U64Null, &person.U64NullUp)
	if !obj.txn {
		if err == nil {
			err = obj.makeErr(tx.Commit())
		}
	}
	if err != nil {
		return nil, obj.makeErr(err)
	}
	return person, nil

}

func (obj *spannerImpl) Get_Person_By_Pk(ctx context.Context,
	person_pk Person_Pk_Field) (
	person *Person, err error) {

	var __embed_stmt = __sqlbundle_Literal("SELECT people.pk, people.name, people.u64, people.u64_up, people.u64_null, people.u64_null_up FROM people WHERE people.pk = ?")

	var __values []any
	__values = append(__values, person_pk.value())

	var __stmt = __sqlbundle_Render(obj.dialect, __embed_stmt)
	obj.logStmt(__stmt, __values...)

	person = &Person{}
	err = obj.driver.QueryRowContext(ctx, __stmt, __values...).Scan(&person.Pk, &person.Name, &person.U64, &person.U64Up, &person.U64Null, &person.U64NullUp)
	if err != nil {
		return (*Person)(nil), obj.makeErr(err)
	}
	return person, nil

}

func (obj *spannerImpl) Get_Person_By_U64_And_U64Up_And_U64Null_And_U64NullUp(ctx context.Context,
	person_u64 Person_U64_Field,
	person_u64_up Person_U64Up_Field,
	person_u64_null Person_U64Null_Field,
	person_u64_null_up Person_U64NullUp_Field) (
	person *Person, err error) {

	var __cond_0 = &__sqlbundle_Condition{Left: "people.u64_null", Equal: true, Right: "?", Null: true}
	var __cond_1 = &__sqlbundle_Condition{Left: "people.u64_null_up", Equal: true, Right: "?", Null: true}

	var __embed_stmt = __sqlbundle_Literals{Join: "", SQLs: []__sqlbundle_SQL{__sqlbundle_Literal("SELECT people.pk, people.name, people.u64, people.u64_up, people.u64_null, people.u64_null_up FROM people WHERE people.u64 = ? AND people.u64_up = ? AND "), __cond_0, __sqlbundle_Literal(" AND "), __cond_1, __sqlbundle_Literal(" LIMIT 2")}}

	var __values []any
	__values = append(__values, spannerConvertArgument(person_u64.value()), spannerConvertArgument(person_u64_up.value()))
	if !person_u64_null.isnull() {
		__cond_0.Null = false
		__values = append(__values, spannerConvertArgument(person_u64_null.value()))
	}
	if !person_u64_null_up.isnull() {
		__cond_1.Null = false
		__values = append(__values, spannerConvertArgument(person_u64_null_up.value()))
	}

	var __stmt = __sqlbundle_Render(obj.dialect, __embed_stmt)
	obj.logStmt(__stmt, __values...)

	__rows, err := obj.driver.QueryContext(ctx, __stmt, __values...)
	if err != nil {
		return nil, obj.makeErr(err)
	}
	defer __rows.Close()

	if !__rows.Next() {
		if err := __rows.Err(); err != nil {
			return nil, obj.makeErr(err)
		}
		return nil, makeErr(sql.ErrNoRows)
	}

	person = &Person{}
	err = __rows.Scan(&person.Pk, &person.Name, &person.U64, &person.U64Up, &person.U64Null, &person.U64NullUp)
	if err != nil {
		return nil, obj.makeErr(err)
	}

	if __rows.Next() {
		return nil, tooManyRows("Person_By_U64_And_U64Up_And_U64Null_And_U64NullUp")
	}

	if err := __rows.Err(); err != nil {
		return nil, obj.makeErr(err)
	}

	return person, nil

}

func (obj *spannerImpl) Update_Person_By_Pk_And_U64_And_U64Up_And_U64Null_And_U64NullUp(ctx context.Context,
	person_pk Person_Pk_Field,
	person_u64 Person_U64_Field,
	person_u64_up Person_U64Up_Field,
	person_u64_null Person_U64Null_Field,
	person_u64_null_up Person_U64NullUp_Field,
	update Person_Update_Fields) (
	person *Person, err error) {

	var __sets = &__sqlbundle_Hole{}
	var __cond_0 = &__sqlbundle_Condition{Left: "people.u64_null", Equal: true, Right: "?", Null: true}
	var __cond_1 = &__sqlbundle_Condition{Left: "people.u64_null_up", Equal: true, Right: "?", Null: true}

	var __embed_stmt = __sqlbundle_Literals{Join: "", SQLs: []__sqlbundle_SQL{__sqlbundle_Literal("UPDATE people SET "), __sets, __sqlbundle_Literal(" WHERE people.pk = ? AND people.u64 = ? AND people.u64_up = ? AND "), __cond_0, __sqlbundle_Literal(" AND "), __cond_1, __sqlbundle_Literal(" THEN RETURN people.pk, people.name, people.u64, people.u64_up, people.u64_null, people.u64_null_up")}}

	__sets_sql := __sqlbundle_Literals{Join: ", "}
	var __values []any
	var __args []any

	if update.U64Up._set {
		__values = append(__values, spannerConvertArgument(update.U64Up.value()))
		__sets_sql.SQLs = append(__sets_sql.SQLs, __sqlbundle_Literal("u64_up = ?"))
	}
	if update.U64NullUp._set {
		__values = append(__values, spannerConvertArgument(update.U64NullUp.value()))
		__sets_sql.SQLs = append(__sets_sql.SQLs, __sqlbundle_Literal("u64_null_up = ?"))
	}

	if len(__sets_sql.SQLs) == 0 {
		return nil, emptyUpdate()
	}

	__args = append(__args, person_pk.value(), spannerConvertArgument(person_u64.value()), spannerConvertArgument(person_u64_up.value()))
	if !person_u64_null.isnull() {
		__cond_0.Null = false
		__args = append(__args, spannerConvertArgument(person_u64_null.value()))
	}
	if !person_u64_null_up.isnull() {
		__cond_1.Null = false
		__args = append(__args, spannerConvertArgument(person_u64_null_up.value()))
	}

	__values = append(__values, __args...)
	__sets.SQL = __sets_sql

	var __stmt = __sqlbundle_Render(obj.dialect, __embed_stmt)
	obj.logStmt(__stmt, __values...)

	person = &Person{}
	d := obj.driver
	var tx *sql.Tx
	if !obj.txn {
		tx, err = obj.db.DB.BeginTx(ctx, nil)
		if err != nil {
			return nil, obj.makeErr(err)
		}
		d = tx
		defer func() {
			if txErr := tx.Rollback(); txErr != nil && !errors.Is(sql.ErrTxDone, txErr) {
				err = obj.makeErr(errors.Join(err, txErr))
			}
		}()
	}
	err = d.QueryRowContext(ctx, __stmt, __values...).Scan(&person.Pk, &person.Name, &person.U64, &person.U64Up, &person.U64Null, &person.U64NullUp)
	if !obj.txn {
		if err == nil {
			err = obj.makeErr(tx.Commit())
		}
	}
	if err == sql.ErrNoRows {
		return nil, nil
	}
	if err != nil {
		return nil, obj.makeErr(err)
	}
	return person, nil
}

func (obj *spannerImpl) Delete_Person_By_U64_And_U64Up_And_U64Null_And_U64NullUp(ctx context.Context,
	person_u64 Person_U64_Field,
	person_u64_up Person_U64Up_Field,
	person_u64_null Person_U64Null_Field,
	person_u64_null_up Person_U64NullUp_Field) (
	count int64, err error) {

	var __cond_0 = &__sqlbundle_Condition{Left: "people.u64_null", Equal: true, Right: "?", Null: true}
	var __cond_1 = &__sqlbundle_Condition{Left: "people.u64_null_up", Equal: true, Right: "?", Null: true}

	var __embed_stmt = __sqlbundle_Literals{Join: "", SQLs: []__sqlbundle_SQL{__sqlbundle_Literal("DELETE FROM people WHERE people.u64 = ? AND people.u64_up = ? AND "), __cond_0, __sqlbundle_Literal(" AND "), __cond_1}}

	var __values []any
	__values = append(__values, spannerConvertArgument(person_u64.value()), spannerConvertArgument(person_u64_up.value()))
	if !person_u64_null.isnull() {
		__cond_0.Null = false
		__values = append(__values, spannerConvertArgument(person_u64_null.value()))
	}
	if !person_u64_null_up.isnull() {
		__cond_1.Null = false
		__values = append(__values, spannerConvertArgument(person_u64_null_up.value()))
	}

	var __stmt = __sqlbundle_Render(obj.dialect, __embed_stmt)
	obj.logStmt(__stmt, __values...)

	__res, err := obj.driver.ExecContext(ctx, __stmt, __values...)
	if err != nil {
		return 0, obj.makeErr(err)
	}

	count, err = __res.RowsAffected()
	if err != nil {
		return 0, obj.makeErr(err)
	}

	return count, nil

}

func (impl spannerImpl) isConstraintError(err error) (constraint string, ok bool) {
	return "", false
}

func (obj *spannerImpl) deleteAll(ctx context.Context) (count int64, err error) {
	var __res sql.Result
	var __count int64
	__res, err = obj.driver.ExecContext(ctx, "DELETE FROM people;")
	if err != nil {
		return 0, obj.makeErr(err)
	}

	__count, err = __res.RowsAffected()
	if err != nil {
		return 0, obj.makeErr(err)
	}
	count += __count

	return count, nil

}

type Methods interface {
	Create_Person(ctx context.Context,
		person_name Person_Name_Field,
		person_u64 Person_U64_Field,
		person_u64_up Person_U64Up_Field,
		optional Person_Create_Fields) (
		person *Person, err error)

	Delete_Person_By_U64_And_U64Up_And_U64Null_And_U64NullUp(ctx context.Context,
		person_u64 Person_U64_Field,
		person_u64_up Person_U64Up_Field,
		person_u64_null Person_U64Null_Field,
		person_u64_null_up Person_U64NullUp_Field) (
		count int64, err error)

	Get_Person_By_Pk(ctx context.Context,
		person_pk Person_Pk_Field) (
		person *Person, err error)

	Get_Person_By_U64_And_U64Up_And_U64Null_And_U64NullUp(ctx context.Context,
		person_u64 Person_U64_Field,
		person_u64_up Person_U64Up_Field,
		person_u64_null Person_U64Null_Field,
		person_u64_null_up Person_U64NullUp_Field) (
		person *Person, err error)

	Update_Person_By_Pk_And_U64_And_U64Up_And_U64Null_And_U64NullUp(ctx context.Context,
		person_pk Person_Pk_Field,
		person_u64 Person_U64_Field,
		person_u64_up Person_U64Up_Field,
		person_u64_null Person_U64Null_Field,
		person_u64_null_up Person_U64NullUp_Field,
		update Person_Update_Fields) (
		person *Person, err error)
}

type TxMethods interface {
	Methods

	Rebind(s string) string
	Commit() error
	Rollback() error
}

type txMethods interface {
	TxMethods

	deleteAll(ctx context.Context) (int64, error)
	makeErr(err error) error
}

type DBMethods interface {
	Methods

	Schema() []string
	DropSchema() []string

	Rebind(sql string) string
}

type dbMethods interface {
	DBMethods

	wrapTx(tx *sql.Tx) txMethods
	makeErr(err error) error
}

var sqlite3DriverName = func() string {
	var id [16]byte
	_, _ = rand.Read(id[:])
	return fmt.Sprintf("sqlite3_%x", string(id[:]))
}()

func init() {
	sql.Register(sqlite3DriverName, &sqlite3.SQLiteDriver{
		ConnectHook: sqlite3SetupConn,
	})
}

// SQLite3JournalMode controls the journal_mode pragma for all new connections.
// Since it is read without a mutex, it must be changed to the value you want
// before any Open calls.
var SQLite3JournalMode = "WAL"

func sqlite3SetupConn(conn *sqlite3.SQLiteConn) (err error) {
	_, err = conn.Exec("PRAGMA foreign_keys = ON", nil)
	if err != nil {
		return makeErr(err)
	}
	_, err = conn.Exec("PRAGMA journal_mode = "+SQLite3JournalMode, nil)
	if err != nil {
		return makeErr(err)
	}
	return nil
}

func opensqlite3(source string) (*sql.DB, error) {
	return sql.Open(sqlite3DriverName, source)
}

func openpgx(source string) (*sql.DB, error) {
	return sql.Open("pgx", source)
}

func openpgxcockroach(source string) (*sql.DB, error) {
	// try first with "cockroach" as a driver in case someone has registered
	// some special stuff. if that fails, then try again with "pgx" as
	// the driver.
	db, err := sql.Open("cockroach", source)
	if err != nil {
		db, err = sql.Open("pgx", source)
	}
	return db, err
}

func openspanner(source string) (*sql.DB, error) {
	return sql.Open("spanner", strings.TrimPrefix(source, "spanner://"))
}

func spannerConvertArgument(v any) any {
	switch v := v.(type) {
	case uint64:
		return spannerUint64{val: v}
	case *uint64:
		return spannerPointerUint64{val: v}
	default:
		return v
	}
}

type spannerUint64 struct {
	val uint64
}

func (s spannerUint64) Value() (sqldriver.Value, error) {
	if s.val > math.MaxInt64 {
		return nil, fmt.Errorf("value %d is larger than max supported INT64 column value %d", s.val, math.MaxInt64)
	}
	return int64(s.val), nil
}

type spannerPointerUint64 struct {
	val *uint64
}

func (s spannerPointerUint64) Value() (sqldriver.Value, error) {
	if s.val == nil {
		return nil, nil
	}
	if *s.val > math.MaxInt64 {
		return nil, fmt.Errorf("value %d is larger than max supported INT64 column value %d", *s.val, math.MaxInt64)
	}
	return int64(*s.val), nil
}
