-- AUTOGENERATED BY storj.io/dbx
-- DO NOT EDIT
CREATE TABLE people (
	pk bigserial NOT NULL,
	name text NOT NULL,
	u64 bigint NOT NULL,
	u64_up bigint NOT NULL,
	u64_null bigint,
	u64_null_up bigint,
	PRIMARY KEY ( pk )
)
