-- AUTOGENERATED BY storj.io/dbx
-- DO NOT EDIT
CREATE TABLE consumed_serials (
	expires_at TIMESTAMP NOT NULL,
	storage_node_id BYTES(MAX) NOT NULL,
	project_id BYTES(MAX) NOT NULL,
	bucket_name BYTES(MAX) NOT NULL,
	action INT64 NOT NULL,
	serial_number BYTES(MAX) NOT NULL,
	settled INT64 NOT NULL
) PRIMARY KEY ( expires_at, storage_node_id, project_id, bucket_name, action, serial_number )
